### ISSUE TITLE
Can we remove numpy<2 in requirements and just push to numpy? 

### ISSUE THREAD

**Issue by JohnOmernik** [zhihanyue/qgridnext#11]
It looks like numpy is pinned in the requirements.txt file (https://github.com/zhihanyue/qgridnext/blob/main/requirements.txt)

to

numpy<2 

Any reason this is pinned to numpy <2?  Can we just have numpy be the requirement? 

Thank you!

**Comment by zhihanyue** [comment]
Thank you! I'll fix it.
