### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by jnaylor92** [zhihanyue/qgridnext#5]
How feasible is it to get pagination support?

**Comment by jnaylor92** [comment]
Is the number of elements loaded by the lazy loading configurable? Thanks for the ID narrowing suggestion, might look into it

**Comment by zhihanyue** [comment]
> Is the number of elements loaded by the lazy loading configurable? Thanks for the ID narrowing suggestion, might look into it

No, the page size is hardcoded to 100. Specifically, when we scroll to the page boundary, It loads data from i-100 to i+100 for position i.
