### ISSUE TITLE
The last row is partially cut off when using customized grid_options

### ISSUE THREAD

**Issue by auriz24** [zhihanyue/qgridnext#8]
### Environment

* Operating System: Debian GNU/Linux 12 (bookworm)
* Python Version: Python 3.11.9
* Python packages: 
```
anyio==4.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==24.2.0
babel==2.16.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
comm==0.2.2
debugpy==1.8.5
decorator==5.1.1
defusedxml==0.7.1
executing==2.0.1
fastjsonschema==2.20.0
fqdn==1.5.1
gitdb==4.0.11
GitPython==3.1.41
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
ipykernel==6.29.5
ipython==8.26.0
ipywidgets==8.1.3
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.4
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.11
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.0.2
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
notebook==7.2.1
notebook_shim==0.2.4
numpy==1.26.4
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
platformdirs==4.2.2
prometheus_client==0.20.0
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
pycparser==2.22
Pygments==2.18.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.1
PyYAML==6.0.2
pyzmq==26.1.1
qgridnext==2.0.1
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.20.0
Send2Trash==1.8.3
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
terminado==0.18.1
tinycss2==1.3.0
tornado==6.4.1
traitlets==5.14.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
tzdata==2024.1
uri-template==1.3.0
urllib3==2.2.2
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.11
```

* Jupyter lab packages (if applicable):
```
JupyterLab v4.2.4
/home/vscode/.local/share/jupyter/labextensions
        qgridnext v2.0.1 enabled OK (python, qgridnext)
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.11 enabled OK (python, jupyterlab_widgets)
        @jupyter-notebook/lab-extension v7.2.1 enabled OK
```

### Description of Issue

The last row is partially cut off when using customized `grid_options` such as disabling column autofit, `{'forceFitColumns': False}`.

* What did you expect to happen? _The last row to be fully visible._
* What happened instead? _The last row was barely visible. It's hiding behind the horizontal scrollbar. That scrollbar is expected if all columns don't fit on the screen. It's not expected if all columns fit on the screen, though. Nevertheless, that scrollbar was placed on top of the grid instead of being stacked. I do not recall this being an issue in the original Qgrid package._

Examples:

![image](https://github.com/user-attachments/assets/10d0a2af-ada7-4652-ae49-5fca39f87034)
_A large dataset (100 rows, 30 columns)_

![image](https://github.com/user-attachments/assets/8134886b-75b3-4f76-9734-1cd9501e7799)
_A smaller dataset (100 rows, 3 columns)_

### Reproduction Steps

1. Disable column autofit, `qgrid.show_grid(..., grid_option={'forceFitColumns': False})`.

### What steps have you taken to resolve this already?

Not applicable.

### Anything else?

Not applicable.

**Comment by auriz24** [comment]
I'd like to post a few more examples showcasing the issue and comparing it to the old Qgrid package.

**Qgrid**

_Environment: Jupyter Notebook 6.5.7, ipywidgets 7.8.5, qgrid 1.3.1_

The last row is fully visible when using the old Qgrid package:

![Screenshot 2024-10-25 143133](https://github.com/user-attachments/assets/c739fea2-2f58-4cca-a10b-3ae55e1e27e0)

The grid canvas and the horizontal slider are stacked properly:

![Screenshot 2024-10-25 143342](https://github.com/user-attachments/assets/e87f704d-0bbd-4e72-9317-6e6a5bb30def)

**QgridNext**

_Environment: Jupyter Notebook 7.2.2, ipywidgets 8.1.5, qgridnext 2.0.1_

The last row is partially visible when using the new QgridNext package:

![Screenshot 2024-10-25 150841](https://github.com/user-attachments/assets/a0754e26-19fd-4d7b-bf9c-814ed0ff08cb)

The grid canvas and horizontal slider are **not** stacked. Instead, the slider is layered on top of the grid canvas:

![Screenshot 2024-10-25 151053](https://github.com/user-attachments/assets/6fb79319-cd7a-4f0f-a480-4fda45fb1ca5)

_Notes: The environments are not identical because Qgrid 1.3.1 doesn't work with ipywidgets 8 and notebook 7._

**Comment by zhihanyue** [comment]
I'm investigating this issue. With notebook 7, qgridnext displays properly in macOS browsers (Safari & Chrome), but I was able to reproduce the problem in Windows browsers (Edge & Chrome). This should be related to the notebook version, as qgridnext also displays properly with notebook 6.

**Comment by zhihanyue** [comment]
I tracked down the issue to inconsistent scrollbar dimension measurements in newer Jupyter environments. The next release will fix this issue.
