### ISSUE TITLE
Jupyter widgets CSS overflow override

### ISSUE THREAD

**Issue by azjps** [zhihanyue/qgridnext#9]
### Environment

* Operating System:
* Python Version: `python3.8.19`
* Python packages: `qgridnext==2.0.1 jupyterlab==3.6.8 ipywidgets==8.1.5`

### Description of Issue

Hi, thanks for maintaining this package. The following CSS entry in `js/src/qgrid.css` causes issues with `ipywidgets` (see for example https://github.com/jupyter-widgets/ipywidgets/issues/3011):
```css
.jupyter-widgets {
    overflow: auto !important;
}
```
It was originally added for [JupyterLab 1.1](https://github.com/quantopian/qgrid/pull/275/files), there isn't an explanation of why it was added then but I'm pretty sure its no longer relevant.

Here's a couple of example screenshots showing the effect on `ipywidgets.Button` when this CSS setting is toggled:
<img width="1253" alt="image" src="https://github.com/user-attachments/assets/a9c31fb5-177f-4c6a-ae44-041a5062b161">
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/30ebfbca-7893-4d44-8591-cca7552c32c3">

Would it be okay to remove this line from the CSS file?

**Comment by zhihanyue** [comment]
Thanks for reporting this. I will fix it in the next release.
